### PR TITLE
Update configuration for Typescript

### PR DESCRIPTION
**Pull request by MeloHenrique**
For the typescript update to work, we need to change the configuration.
I've changed the "package.json" file and compiled the package.
I also updated the version to these changes show up in npm. (Not sure if this is necessary).

### CODE REVIEW

**Comment by MeloHenrique** [comment]
I've made a few updates on my fork because I couldn't use this package nor with webpack or Cloudflare. 
To fix it, I had to remove the json-colorizer package. I don't know if these changes are of any interest so let me know if you want a new pull request. (I think that after these changes, there's nothing more to do)

**Comment by MeloHenrique** [comment]
@michaelwclark Hello, can you check this pull request?

**Comment by michaelwclark** [comment]
@MeloHenrique sorry about the delay.

**Comment by michaelwclark** [comment]
> I've made a few updates on my fork because I couldn't use this package nor with webpack or Cloudflare. To fix it, I had to remove the json-colorizer package. I don't know if these changes are of any interest so let me know if you want a new pull request. (I think that after these changes, there's nothing more to do)

I'd be open to that. That package is not at all required for functionality of this project. I added it only for prettier output in my console runs.

**Pull request merged**
